### ISSUE TITLE
【HELP】有没有推荐的分线器？

### ISSUE THREAD

**Issue by ZhouYixun** [alibaba/taobao-iphone-device#102]
线使用了作者推荐的绿联线，但是连接20台手机还是发生很高的断线率，一晚下来只有一个存活。分线器的话有推荐吗

**Comment by codeskyblue** [comment]
我目前用的是这个  https://item.jd.com/4576040.html#crumb-wrap

不过只是因为公司给发的就是这个（其实我个人感觉只要是 USB单独供电的都可以）

**Comment by codeskyblue** [comment]
https://item.jd.com/11094070848.html
这个看起来也行（没试过）

**Comment by ZhouYixun** [comment]
> https://item.jd.com/11094070848.html
> 这个看起来也行（没试过）

你们一台mac mini能带起多少台ios使用tidevice？我这边带4台以上，就开始各种wda断连的情况，需要额外处理usbmuxd吗？

**Comment by weikilla** [comment]
> > https://item.jd.com/11094070848.html
> > 这个看起来也行（没试过）
> 
> 你们一台mac mini能带起多少台ios使用tidevice？我这边带4台以上，就开始各种wda断连的情况，需要额外处理usbmuxd吗？

请问有对比过使用tidevice，会比使用xcodebuild能拖更多的设备吗

**Comment by slimsymphony** [comment]
![image](https://user-images.githubusercontent.com/331607/126735487-8e0137f3-7c86-412b-a484-1ae188561cb4.png)

**Comment by codeskyblue** [comment]
作者很穷的。最近换了一个组，现在能有4台iphone手机就不错了。
