### ISSUE TITLE
PermissionError: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by yangeren** [alibaba/taobao-iphone-device#117]
每次跑完脚本，要重新再跑一次时，就出现无权限，需要使用sudo tidevice执行一次后，才可以重新跑，这是啥原因？
![tidevice_error](https://user-images.githubusercontent.com/3181945/122339802-175c1a00-cf74-11eb-8da4-bd4b5e1b90b2.jpg)

**Comment by jongyu** [comment]
这个是你自己安装的问题吧,和tidevice没有关系

**Comment by yangeren** [comment]
自己解答：发现问题出在`~/.tidevice/ssl`目录中文件的归属权限，将`ssl`目录设置成执行用户权限`sudo chown -R user:group ssl` 即可解决，有遇到此问题的同学可以参考一波；
目前只发现了临时解决方案，还没发现为什么有一部分是root，一部分是其他用户的。
