### ISSUE TITLE
找不到iOS14.4.zip文件

### ISSUE THREAD

**Issue by jongyu** [alibaba/taobao-iphone-device#12]
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://tool.appetizer.io/iGhibli/iOS-DeviceSupport/raw/master/DeviceSupport/14.4.zip
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://github.com/iGhibli/iOS-DeviceSupport/raw/master/DeviceSupport/14.4.zip
自动webdriverrunner时报找不到文件，下载地址里面没有对应文件，但是里面的iOS14文件名包含其他的内容，我感觉你们时没有测iOS14的设备？
https://tool.appetizer.io/iGhibli/iOS-DeviceSupport/tree/master/DeviceSupport

**Comment by jongyu** [comment]
![image](https://user-images.githubusercontent.com/26176468/106372530-86611980-63ab-11eb-8cbf-72f733164752.png)

**Comment by jongyu** [comment]
![image](https://user-images.githubusercontent.com/26176468/106372539-97118f80-63ab-11eb-8b12-91588e081485.png)

**Comment by codeskyblue** [comment]
fixed in tidevice 0.1.4

**Comment by electricbubble** [comment]
😭 刚 `fork` 想提交蹭一个贡献者, 就被修复了

**Comment by codeskyblue** [comment]
> 😭 刚 `fork` 想提交蹭一个贡献者, 就被修复了

There are still many chances

**Comment by jongyu** [comment]
大佬速度快得很嘛，我看你源码后，我自己通过Mac上的镜像拷贝过去了。项目很不错，如果可以把iproxy工具加进入进去就好了，弄了一天发现，Appium跑不起来，应该是appium有做环境判断，提示`An unknown server-side error occurred while processing the command. Original error: Could not determine Xcode version: Could not find path to Xcode by symlinks located in /var/db/xcode_select_link, or /usr/share/xcode-select/xcode_dir_link` ， 希望大佬给appium那边提个需求，那样就无敌了，我也看了facebook-wda的源码，它是自己调接口启动的xctest，没有像appium做了系统判断

**Comment by jongyu** [comment]
对了，windows下我是用`libimobiledevice` Windows版本的 里面包含了`iproxy.exe`工具,可以通过它转发端口
https://github.com/libimobiledevice-win32/imobiledevice-net/releases/
