### ISSUE TITLE
fsync功能失效命令如下：tidevice fsync -B BUNDLEID ls ./

### ISSUE THREAD

**Issue by wangjiawei9816** [alibaba/taobao-iphone-device#124]
![98JE486P`%UB)DX9)SNJ01W](https://user-images.githubusercontent.com/18022629/128187572-4c05a5c2-3480-4107-b41c-f31f23ac99f8.png)

**Comment by wangjiawei9816** [comment]
多人都有此问题，疑似协议不匹配，麻烦官方的人验证一下：
window系统下，使用tidevice的fsync进行访问指定bundle的任何文件夹，都会报错

**Comment by wangjiawei9816** [comment]
还是一样的报错，并且多人复现在ios14.5以上的版本

**Comment by wangjiawei9816** [comment]
https://github.com/alibaba/taobao-iphone-device/issues/100 同样的问题，可能是magic失效了

**Comment by codeskyblue** [comment]
你们的好像不太一样，我现在手机还没升级到14.5..  App的list需要App设置了 可以访问沙盒的权限才可以

**Comment by wangjiawei9816** [comment]
得在windows系统下，你是不是在mac机上的，，

**Comment by codeskyblue** [comment]
是的，我用的Mac M1

**Comment by wangjiawei9816** [comment]
你可以尝试一下windows机器，必定报错，我们很多用户都是因为它能在Windows平台使用才选择tidevice的，如果可以，请帮忙查一下问题，我也可以帮忙辅助查问题

**Comment by wangjiawei9816** [comment]
可以参考这个地方修改，_device.py搜索vendcontainer改成venddocuments即可
https://github.com/GNOME/gvfs/commit/b8ad223b1e2fbe0aec24baeec224a76d91f4ca2f

**Comment by codeskyblue** [comment]
Fixed in tidevice 0.4.15. Thanks @wangjiawei9816

**Comment by wangjiawei9816** [comment]
直接改会有一个问题，listdir（‘/tmp’）失败，得区分不同情况
