### ISSUE TITLE
采集不到cpu和内存信息

### ISSUE THREAD

**Issue by JennyPan2016** [alibaba/taobao-iphone-device#131]
采集不到cpu和内存数据，只有fps、screenshot、network三个。
<img width="766" alt="iShot2021-08-19 20 55 35" src="https://user-images.githubusercontent.com/21152964/130072152-dedb1645-5d76-469c-b6f6-a4af616aed20.png">

**Comment by codeskyblue** [comment]
看看bundleId传的对不对

**Comment by JennyPan2016** [comment]
是打包的问题，已解决。
