### ISSUE TITLE
获取不到iphone list.

### ISSUE THREAD

**Issue by 382140857** [alibaba/taobao-iphone-device#15]
![image](https://user-images.githubusercontent.com/18543073/106552811-f9f15b00-6552-11eb-917a-af703eca7513.png)

**Comment by electricbubble** [comment]
https://github.com/alibaba/taobao-iphone-device/issues/4#issuecomment-769544573

**Comment by 382140857** [comment]
感谢。原来还有前置步骤。

**Comment by 382140857** [comment]
> [#4 (comment)](https://github.com/alibaba/taobao-iphone-device/issues/4#issuecomment-769544573)

多谢
