### ISSUE TITLE
Possible to launch app with process argument

### ISSUE THREAD

**Issue by krishtoautomate** [alibaba/taobao-iphone-device#157]
we are able launch app with
tidevice launch com.example.demo

is it possible to improve it with lauch app with process arguments?

tidevice launch com.example.demo {"args" : ["FLAG"], "env" : {}}

**Comment by codeskyblue** [comment]
`tidevice launch com.example.demo -- arg0 arg1`

**Comment by codeskyblue** [comment]
tidevice launch --help to see more usage
