### ISSUE TITLE
长时间运行测试获取内存数据报错[Errno 32] Broken pipe

### ISSUE THREAD

**Issue by youshuchang** [alibaba/taobao-iphone-device#159]
tidevice 版本：0.5.3
python版本：3.9
iOS版本：iOS 14.2

![image](https://user-images.githubusercontent.com/10020516/141740250-a0cbad67-a3fe-4c3b-9030-6ad4139b1289.png)
代码：
循环执行功能测试用例，每次执行测试用例前调用一次图中的这个方法获取内存，也就是测试过程中会反复的perf.start()，perf.stop()
![image](https://user-images.githubusercontent.com/10020516/141740464-c82350b7-a06e-4328-ae1e-b96ce5bcaa15.png)

**Comment by codeskyblue** [comment]
possible duplicated with https://github.com/alibaba/taobao-iphone-device/issues/148
