### ISSUE TITLE
关于设备信息获取的两个建议

### ISSUE THREAD

**Issue by 554632107** [alibaba/taobao-iphone-device#163]
tidevice list --json可以获取多个连接设备的uuid和name，可不可以加个iOS系统版本号？
tidevice info 只能获取单个设备的信息，能否优化一下获取多个连接设备的详细信息？
谢谢

**Comment by codeskyblue** [comment]
tidevice list --json 这个已经加上去了。tidevice info 暂时先不动了，一个个的获取好了
