### ISSUE TITLE
Mac上安装tidevice后，在iTerm执行tidevice version报错zsh: command not found: tidevice

### ISSUE THREAD

**Issue by shuiming-he** [alibaba/taobao-iphone-device#197]
求大佬帮忙解答

**Comment by codeskyblue** [comment]
没有加环境变量吧，可以先用 python3 -m tidevice -h 代替

**Comment by zys520** [comment]
代替后依然出现这个错误

**Comment by zys520** [comment]
配置环境变量
vim ～/.bash_profile
添加export PATH="$PATH:自己的路径（于上方绿色框住路径一致）"
例如export PATH="$PATH:/Users/xm/Library/Python/3.9/bin"
保存退出后source ～/.bash_profile就好了
