### ISSUE TITLE
用relay一直卡着不能转发端口

### ISSUE THREAD

**Issue by metoto** [alibaba/taobao-iphone-device#20]
win10系统，不确认为什么无法用relay去转发端口，之前用linux，iproxy是正常的。
这个是系统兼容的问题么？防火墙都关了。

**Comment by jongyu** [comment]
直接使用`tidevice wdaproxy --port 8100`就好咯，你使用`tidevice relay`转发的端口使用在本地使用，无法通过别的别的机器访问，用`tidevice wdaproxy`就没这个问题，`iproxy `代理出来的也是只能在本地使用，`tidevice wdaproxy`测试了是没问题的

**Comment by mp55** [comment]
我不行  救命
[image](https://github.com/mp55/test/blob/main/3.png)

**Comment by codeskyblue** [comment]
啥问题啊，你文字描述一下

**Comment by codeskyblue** [comment]
没有后续，我就先关掉issue啦
