### ISSUE TITLE
ps  sysinfo launch等部分命令无法使用

### ISSUE THREAD

**Issue by FaanJoeng** [alibaba/taobao-iphone-device#200]
win11 + tidevice 0.6.13 + ios 15.4
确认手机已连接，iTunes已启动，tidevice applist 可以执行 tidevice ps 及tidevice sysinfo无法执行，疑似与com.apple.instruments.server.services.deviceinfo com.apple.instruments.server.services.processcontrol 两个通道有关，不能稳定复现，偶尔可以正常使用
报错如下：
![image](https://user-images.githubusercontent.com/14855496/160315583-62c16a62-61ee-43d7-8df4-545f4bcdd4b7.png)

**Comment by FaanJoeng** [comment]
试了下idb 貌似也启动不了
![image](https://user-images.githubusercontent.com/14855496/160349006-359ff53d-9571-4cb5-a60d-0283e9ecc69f.png)

**Comment by codeskyblue** [comment]
已知问题，换tidevice 0.7.4 手机重启一下就好了
