### ISSUE TITLE
tidevice version 0.7.2 版本，iPhone 11 Pro Max 手机，执行`tidevce launch`启动应用会卡住不懂，且无法取消。

### ISSUE THREAD

**Issue by Silence0789** [alibaba/taobao-iphone-device#201]
![image](https://user-images.githubusercontent.com/35662458/160971780-6396c812-5608-4a47-8158-96fd19b940c7.png)

您好，如上图，最近我在tidevice升级至0.7.1、0.7.2版本后，发现执行`tidevice launch`、`tidevice kill`等命令时，命令会卡住、执行不下去了（输出如上图），并且此时按`ctrl+c`无法中断取消。然后再将tidevice降级至0.6.4版本，再执行这2个命令，发现执行正常。

手机是 iPhone 11 Pro Max，系统版本 iOS 15.4，型号号码 MWEX2CH/A。

请排查。

**Comment by Silence0789** [comment]
刚发现把tidevice卸载重装一下，我这个问题正常了。所以没搞明白情况，但我这个问题不用处理了。

**Comment by codeskyblue** [comment]
升级到0.7.4 以后试试，这个其实还是个资源释放的bug，已经修复。

**Comment by Silence0789** [comment]
目前卸载重装后没有在遇到这个问题了，升级到最新版也没有此问题了，所以应该是解决了。谢谢修复。
