### ISSUE TITLE
win10 /m1 mac下 每30秒一次started fail，最后程序退出(已排除数据线问题)

### ISSUE THREAD

**Issue by j188482367** [alibaba/taobao-iphone-device#232]
(base) hom@homdeMac-mini1 ~ % tidevice -u 7657f0bdfdac7a98049a9f84a069143d7d21c330 wdaproxy -B com.facebook.WebDriverAgentRunner.xctrunner --port 8000
[I 220627 20:59:15 _wdaproxy:125] [7657f0bdfdac7a98049a9f84a069143d7d21c330] WDA check every 30.0 seconds
[D 220627 20:59:15 _wdaproxy:131] [7657f0bdfdac7a98049a9f84a069143d7d21c330] launch WDA
[I 220627 20:59:15 _device:965] BundleID: com.facebook.WebDriverAgentRunner.xctrunner
[I 220627 20:59:15 _device:981] ProductVersion: 14.6
[I 220627 20:59:15 _device:982] DeviceIdentifier: 7657f0bdfdac7a98049a9f84a069143d7d21c330
[I 220627 20:59:16 _device:816] SignIdentity: 'Apple Development: junhong liu (GC2G6B3EW2)'
[I 220627 20:59:16 _device:822] CFBundleExecutable: WebDriverAgentRunner-Runner
[I 220627 20:59:16 _device:853] AppContainer: /private/var/mobile/Containers/Data/Application/BD2A1A62-9E90-48B6-BE97-14531CF30CDE
[I 220627 20:59:16 _device:895] Launch 'com.facebook.WebDriverAgentRunner.xctrunner' pid: 53280
[I 220627 20:59:17 _device:931] WebDriverAgent start successfully
[E 220627 20:59:45 _wdaproxy:150] [7657f0bdfdac7a98049a9f84a069143d7d21c330] wda started failed
[D 220627 20:59:45 _wdaproxy:131] [7657f0bdfdac7a98049a9f84a069143d7d21c330] launch WDA
[I 220627 20:59:46 _device:965] BundleID: com.facebook.WebDriverAgentRunner.xctrunner
[I 220627 20:59:46 _device:981] ProductVersion: 14.6
[I 220627 20:59:46 _device:982] DeviceIdentifier: 7657f0bdfdac7a98049a9f84a069143d7d21c330
[I 220627 20:59:46 _device:816] SignIdentity: 'Apple Development: junhong liu (GC2G6B3EW2)'
[I 220627 20:59:46 _device:822] CFBundleExecutable: WebDriverAgentRunner-Runner
[I 220627 20:59:47 _device:853] AppContainer: /private/var/mobile/Containers/Data/Application/BD2A1A62-9E90-48B6-BE97-14531CF30CDE
[I 220627 20:59:47 _device:895] Launch 'com.facebook.WebDriverAgentRunner.xctrunner' pid: 53287
[I 220627 20:59:47 _device:931] WebDriverAgent start successfully
[E 220627 21:00:16 _wdaproxy:150] [7657f0bdfdac7a98049a9f84a069143d7d21c330] wda started failed
[D 220627 21:00:16 _wdaproxy:131] [7657f0bdfdac7a98049a9f84a069143d7d21c330] launch WDA
[I 220627 21:00:16 _device:965] BundleID: com.facebook.WebDriverAgentRunner.xctrunner
[I 220627 21:00:16 _device:981] ProductVersion: 14.6
[I 220627 21:00:16 _device:982] DeviceIdentifier: 7657f0bdfdac7a98049a9f84a069143d7d21c330
[I 220627 21:00:17 _device:816] SignIdentity: 'Apple Development: junhong liu (GC2G6B3EW2)'
[I 220627 21:00:17 _device:822] CFBundleExecutable: WebDriverAgentRunner-Runner
[I 220627 21:00:17 _device:853] AppContainer: /private/var/mobile/Containers/Data/Application/BD2A1A62-9E90-48B6-BE97-14531CF30CDE
[I 220627 21:00:17 _device:895] Launch 'com.facebook.WebDriverAgentRunner.xctrunner' pid: 53297
[I 220627 21:00:18 _device:931] WebDriverAgent start successfully
[E 220627 21:00:46 _wdaproxy:150] [7657f0bdfdac7a98049a9f84a069143d7d21c330] wda started failed
[D 220627 21:00:46 _wdaproxy:131] [7657f0bdfdac7a98049a9f84a069143d7d21c330] launch WDA
[I 220627 21:00:47 _device:965] BundleID: com.facebook.WebDriverAgentRunner.xctrunner
[I 220627 21:00:47 _device:981] ProductVersion: 14.6
[I 220627 21:00:47 _device:982] DeviceIdentifier: 7657f0bdfdac7a98049a9f84a069143d7d21c330
[I 220627 21:00:47 _device:816] SignIdentity: 'Apple Development: junhong liu (GC2G6B3EW2)'
[I 220627 21:00:47 _device:822] CFBundleExecutable: WebDriverAgentRunner-Runner
[I 220627 21:00:47 _device:853] AppContainer: /private/var/mobile/Containers/Data/Application/BD2A1A62-9E90-48B6-BE97-14531CF30CDE
[I 220627 21:00:48 _device:895] Launch 'com.facebook.WebDriverAgentRunner.xctrunner' pid: 53309
[I 220627 21:00:48 _device:931] WebDriverAgent start successfully
[E 220627 21:01:17 _wdaproxy:150] [7657f0bdfdac7a98049a9f84a069143d7d21c330] wda started failed
[D 220627 21:01:17 _wdaproxy:131] [7657f0bdfdac7a98049a9f84a069143d7d21c330] launch WDA
[I 220627 21:01:17 _device:965] BundleID: com.facebook.WebDriverAgentRunner.xctrunner
[I 220627 21:01:17 _device:981] ProductVersion: 14.6
[I 220627 21:01:17 _device:982] DeviceIdentifier: 7657f0bdfdac7a98049a9f84a069143d7d21c330
[I 220627 21:01:18 _device:816] SignIdentity: 'Apple Development: junhong liu (GC2G6B3EW2)'
[I 220627 21:01:18 _device:822] CFBundleExecutable: WebDriverAgentRunner-Runner
[I 220627 21:01:18 _device:853] AppContainer: /private/var/mobile/Containers/Data/Application/BD2A1A62-9E90-48B6-BE97-14531CF30CDE
[I 220627 21:01:18 _device:895] Launch 'com.facebook.WebDriverAgentRunner.xctrunner' pid: 53317
[I 220627 21:01:19 _device:931] WebDriverAgent start successfully
[E 220627 21:01:48 _wdaproxy:150] [7657f0bdfdac7a98049a9f84a069143d7d21c330] wda started failed

28秒自动断一次。 3台m1 mac ,一台win10 ,只有其中一台m1 正常

**Comment by xiaoMGitHub** [comment]
我也遇到这情况，用这两条命令启动就没问题
tidevice xctest -B com.facebook.wda.WebDriverAgent.Runner
tidevice relay 8100 8100

**Comment by j188482367** [comment]
> Runner

不玩window了，现在用m1 mini 一带20

**Comment by codeskyblue** [comment]
fixed in 0.9.7
