### ISSUE TITLE
tidevice crashreport 支持导出指定崩溃文件吗

### ISSUE THREAD

**Issue by KJC1999** [alibaba/taobao-iphone-device#283]
[I 230213 17:43:56 _crash:23] List of crash logs
`-- /
    |-- NetworkingTopic-2023-02-13-173229.ips
    |-- CloudServicesTopic-2023-02-13-173226.ips
    |-- TransparencyTopic-2023-02-13-173232.ips
    |-- wpsoffice-2023-02-13-173208.ips
    `-- KeySyncTopic-2023-02-13-173233.ips

我想专门导出wpsoffice的ips文件，但从代码上看似乎没有提供相关参数？有大佬能解答一下吗

**Comment by KJC1999** [comment]
另外群的答案好像改了，不是ios，有大佬知道答案吗

**Comment by codeskyblue** [comment]
32 @KJC1999

**Comment by codeskyblue** [comment]
先导出出来再过滤好了
