### ISSUE TITLE
tidevice 能否支持无线驱动wda？

### ISSUE THREAD

**Issue by gjs1990717** [alibaba/taobao-iphone-device#284]
我通过xcode无线模式连接iphone，然后执行tidevice -u 00008101-001E29662204001E wdaproxy -B com.facebook.WebDriverAgentRunner.xctrunner --port 8105 
报错！！request error: ('Connection aborted.', MuxReplyError(<UsbmuxReplyCode.BadDevice: 2>))
是不支持无线么？？

**Comment by codeskyblue** [comment]
是的，还不支持无线。

**Comment by zhengdemeng** [comment]
麻烦问下通过xcode虚拟的模拟器，是不是也不支持tidevice命令启动wda

**Comment by codeskyblue** [comment]
不支持模拟器
