### ISSUE TITLE
WebDriverAgent: 如何修改在手机上的端口而非电脑端口

### ISSUE THREAD

**Issue by pppppino** [alibaba/taobao-iphone-device#304]
tidevice wdaproxy -B com.facebook.wda.WebDriverAgent.Runner --port 8200
当使用 --port 的时候， 好像只能使得电脑上的端口为 8200， 而**手机上的端口还是 8100**；
我在手机浏览器只有请求 localhost:8100/status 才有返回

所以想问， 有没有什么方式修改 webdriveragent 启动在手机上的端口

**Comment by pppppino** [comment]
这个可能不太适合我 我要同时起多个 driver， 可能需要能够可控的去控制这个端口

**Comment by NoneTypeCoder** [comment]
@pppppino tidevice wdaproxy -B com.facebook.wda.WebDriverAgent.Runner --port 8200 这个命令应该是修改手机上的端口  可以看下README里面的接口介绍

**Comment by pppppino** [comment]
@NoneTypeCoder 谢谢 确实可以这样操作

**Comment by NoneTypeCoder** [comment]
@pppppino 你知道有什么方法可以查看wda在ios手机上占用的端口是多少吗？

**Comment by pppppino** [comment]
@NoneTypeCoder 这个很简单哦 在手机浏览器输入： localhost:端口号/status 即可， 有信息说明是该端口

**Comment by NoneTypeCoder** [comment]
@pppppino 可以在ios手机上用不同端口启动多个不同的wda 比如wda1在手机上启动占用8100  wda2在手机上启动占用8200 然后在windows上通过facebook-wda分别给手机上两个wda发送指令吗？

**Comment by pppppino** [comment]
@NoneTypeCoder 理论上是可以的 没试过， 为什么会有这样的需求呢？ 不能用两个手机去交互吗 这样的话是两个 driver 也很方便

**Comment by pppppino** [comment]
@NoneTypeCoder 这个也是有的哦， 可以通过 driver.excute_script() 来操作， 具体可参照 https://github.com/appium/appium-xcuitest-driver/blob/master/docs/execute-methods.md

**Comment by NoneTypeCoder** [comment]
@pppppino tidevice+facebook-wda在win端做ios自动化测试 发送请求到本机某个端口然后转发到手机上  这个转发是tidevice提供的吧？facebook-wda有转发的功能吗，还是只有构造并发送请求到本机某个端口的功能。
