### ISSUE TITLE
http://localhost:8100/inspecto 無法使用

### ISSUE THREAD

**Issue by pickywu** [alibaba/taobao-iphone-device#33]
tidevice wdaproxy -B com.facebook.wda.WebDriverAgent.Runner --port 8100 送出後，可以正常使用 facebook-wda
但開啟"http://localhost:8100/inspecto"  無法顯示UI圖層
{
  "value" : {
    "error" : "unknown command",
    "message" : "Unhandled endpoint: \/inspector -- http:\/\/localhost:8100\/ with parameters {\n    wildcards =     (\n        inspector\n    );\n}",
    "traceback" : ""
  },
  "sessionId" : "9B60EDE7-2C28-4F4B-9222-67B13EB8865F"
}
或者是否有其他方式可以檢視UI圖層呢?感謝

**Comment by electricbubble** [comment]
https://github.com/appium/WebDriverAgent/issues/367

**Comment by pickywu** [comment]
所以如果要檢視APP元素，是否只能用APPIUM連接去看了?

**Comment by codeskyblue** [comment]
还可以用weditor  https://github.com/openatx/weditor
