### ISSUE TITLE
tidevice 通过哪个函数获取当前设备的market_name (python 调用情况下)

### ISSUE THREAD

**Issue by xaioxu** [alibaba/taobao-iphone-device#334]
python 调用 tidevice库的的方式下，通过device_info func 没有看到market_name 的info

**Comment by xaioxu** [comment]
不用了，直接copy 源码就有哈哈哈哈

**Comment by shamrock33** [comment]
> 不用了，直接copy 源码就有哈哈哈哈

什么意思。。。我也遇到这个问题怎么拿到market_name
