### ISSUE TITLE
 'NoneType' object has no attribute 'conversation_index'

### ISSUE THREAD

**Issue by lvxy-git** [alibaba/taobao-iphone-device#76]
# wdaproxy log：
[D 210420 20:30:49 _relay:36] handle stream from: ('127.0.0.1', 49740)
[I 210420 20:30:50 _device:1116] xctrunner quited
[I 210420 20:30:50 _wdaproxy:104] [00008030-0005119A1AE9802E] WDA keeper stopped
[I 210420 20:30:50 _wdaproxy:132] [00008030-0005119A1AE9802E] WDA stopped for the 2st time, running 1586.4 minutes
[D 210420 20:30:50 _wdaproxy:116] [00008030-0005119A1AE9802E] launch WDA
[D 210420 20:30:50 _relay:36] handle stream from: ('127.0.0.1', 49748)
[E 210420 20:30:50 _relay:46] connect to device error: UsbmuxReplyCode.ConnectionRefused
[D 210420 20:30:50 _relay:36] handle stream from: ('127.0.0.1', 49750)
[E 210420 20:30:50 _relay:46] connect to device error: UsbmuxReplyCode.ConnectionRefused
[I 210420 20:30:50 _device:990] BundleID: com.facebook.WebDriverAgentRunner.lxytest.xctrunner
[I 210420 20:30:50 _device:992] DeviceIdentifier: 00008030-0005119A1AE9802E
[I 210420 20:30:51 _device:834] SignIdentity: 'Apple Development: 旭阳 吕 (G4QRHP58T3)'
[I 210420 20:30:51 _device:840] CFBundleExecutable: WebDriverAgentRunner-Runner
[D 210420 20:30:51 _relay:36] handle stream from: ('127.0.0.1', 49772)
[E 210420 20:30:51 _relay:46] connect to device error: UsbmuxReplyCode.ConnectionRefused
[I 210420 20:30:51 _device:871] AppContainer: /private/var/mobile/Containers/Data/Application/E8AF4528-27DD-48F2-B2BB-43E25BBDEC5E
[I 210420 20:30:52 _device:911] Launch 'com.facebook.WebDriverAgentRunner.lxytest.xctrunner' pid: 6954
[I 210420 20:30:52 _device:1086] ProductVersion: 14.0
[I 210420 20:30:52 _device:1041] Test runner ready detected
[I 210420 20:30:52 _device:1034] Start execute test plan with IDE version: 29
[I 210420 20:30:53 _device:947] WebDriverAgent start successfully
[D 210420 20:33:00 _relay:36] handle stream from: ('127.0.0.1', 50030)
[D 210420 20:33:00 _relay:36] handle stream from: ('127.0.0.1', 50033)
[D 210420 20:34:15 _relay:36] handle stream from: ('127.0.0.1', 50174)
[D 210420 20:35:26 _relay:36] handle stream from: ('127.0.0.1', 50306)
[D 210420 20:36:37 _relay:36] handle stream from: ('127.0.0.1', 50475)
[D 210420 20:37:48 _relay:36] handle stream from: ('127.0.0.1', 50618)
[D 210420 20:39:00 _relay:36] handle stream from: ('127.0.0.1', 50758)
[D 210420 20:40:11 _relay:36] handle stream from: ('127.0.0.1', 50897)
[D 210420 20:41:22 _relay:36] handle stream from: ('127.0.0.1', 51026)
[D 210420 20:42:34 _relay:36] handle stream from: ('127.0.0.1', 51178)
[D 210420 20:43:45 _relay:36] handle stream from: ('127.0.0.1', 51314)
[I 210420 20:43:56 _device:1116] xctrunner quited
[I 210420 20:43:56 _wdaproxy:104] [00008030-0005119A1AE9802E] WDA keeper stopped
[I 210420 20:43:56 _wdaproxy:132] [00008030-0005119A1AE9802E] WDA stopped for the 3st time, running 13.1 minutes
[D 210420 20:43:57 _wdaproxy:116] [00008030-0005119A1AE9802E] launch WDA
[D 210420 20:43:57 _relay:36] handle stream from: ('127.0.0.1', 51350)
[E 210420 20:43:57 _relay:46] connect to device error: UsbmuxReplyCode.ConnectionRefused
[I 210420 20:43:57 _device:990] BundleID: com.facebook.WebDriverAgentRunner.lxytest.xctrunner
[I 210420 20:43:57 _device:992] DeviceIdentifier: 00008030-0005119A1AE9802E
[I 210420 20:43:57 _device:834] SignIdentity: 'Apple Development: 旭阳 吕 (G4QRHP58T3)'
[I 210420 20:43:57 _device:840] CFBundleExecutable: WebDriverAgentRunner-Runner
[D 210420 20:43:57 _relay:36] handle stream from: ('127.0.0.1', 51368)
[E 210420 20:43:57 _relay:46] connect to device error: UsbmuxReplyCode.ConnectionRefused
[I 210420 20:43:58 _device:871] AppContainer: /private/var/mobile/Containers/Data/Application/E8AF4528-27DD-48F2-B2BB-43E25BBDEC5E
[I 210420 20:43:58 _device:911] Launch 'com.facebook.WebDriverAgentRunner.lxytest.xctrunner' pid: 7149
[I 210420 20:43:58 _device:1086] ProductVersion: 14.0
[I 210420 20:43:58 _device:1041] Test runner ready detected
[I 210420 20:43:58 _device:1034] Start execute test plan with IDE version: 29
[D 210420 20:43:58 _relay:36] handle stream from: ('127.0.0.1', 51380)
[E 210420 20:43:58 _relay:46] connect to device error: UsbmuxReplyCode.ConnectionRefused
[I 210420 20:43:58 _device:947] WebDriverAgent start successfully
[D 210420 20:43:58 _relay:36] handle stream from: ('127.0.0.1', 51382)
[D 210420 21:58:55 _relay:36] handle stream from: ('127.0.0.1', 59240)
[D 210420 21:58:55 _relay:36] handle stream from: ('127.0.0.1', 59242)
[D 210420 22:00:09 _relay:36] handle stream from: ('127.0.0.1', 59398)
[D 210420 22:01:21 _relay:36] handle stream from: ('127.0.0.1', 59531)
[D 210420 22:02:32 _relay:36] handle stream from: ('127.0.0.1', 59675)
[D 210420 22:03:43 _relay:36] handle stream from: ('127.0.0.1', 59830)
[D 210420 22:04:55 _relay:36] handle stream from: ('127.0.0.1', 59967)
[I 210420 22:04:55 _device:1116]Exception in thread Thread-2:
Traceback (most recent call last):
  File "d:\python\python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "d:\python\python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "d:\python\python37\lib\site-packages\tidevice\_instruments.py", line 558, in _drain
    self._drain_single_message()
  File "d:\python\python37\lib\site-packages\tidevice\_instruments.py", line 578, in _drain_single_message
    mheader, payload = self.recv_dtx_message()
  File "d:\python\python37\lib\site-packages\tidevice\_instruments.py", line 499, in recv_dtx_message
    assert mheader.conversation_index in [0, 1, 2]
AttributeError: 'NoneType' object has no attribute 'conversation_index'
 xctrunner quited

[I 210420 22:04:55 _wdaproxy:104] [00008030-0005119A1AE9802E] WDA keeper stopped
[I 210420 22:04:55 _wdaproxy:132] [00008030-0005119A1AE9802E] WDA stopped for the 4st time, running 80.9 minutes
[D 210420 22:04:55 _wdaproxy:116] [00008030-0005119A1AE9802E] launch WDA
[D 210420 22:04:55 _relay:36] handle stream from: ('127.0.0.1', 59974)
[E 210420 22:04:55 _relay:46] connect to device error: UsbmuxReplyCode.ConnectionRefused
[D 210420 22:04:55 _relay:36] handle stream from: ('127.0.0.1', 59976)
[E 210420 22:04:55 _relay:46] connect to device error: UsbmuxReplyCode.ConnectionRefused
[I 210420 22:04:56 _device:990] BundleID: com.facebook.WebDriverAgentRunner.lxytest.xctrunner
[I 210420 22:04:56 _device:992] DeviceIdentifier: 00008030-0005119A1AE9802E
[I 210420 22:04:56 _device:834] SignIdentity: 'Apple Development: 旭阳 吕 (G4QRHP58T3)'
[I 210420 22:04:56 _device:840] CFBundleExecutable: WebDriverAgentRunner-Runner
[I 210420 22:04:56 _device:871] AppContainer: /private/var/mobile/Containers/Data/Application/E8AF4528-27DD-48F2-B2BB-43E25BBDEC5E
[D 210420 22:04:56 _relay:36] handle stream from: ('127.0.0.1', 60002)
[E 210420 22:04:56 _relay:46] connect to device error: UsbmuxReplyCode.ConnectionRefused
[I 210420 22:04:56 _device:911] Launch 'com.facebook.WebDriverAgentRunner.lxytest.xctrunner' pid: 8344
[I 210420 22:04:56 _device:1086] ProductVersion: 14.0
[I 210420 22:04:56 _device:1041] Test runner ready detected
[I 210420 22:04:56 _device:1034] Start execute test plan with IDE version: 29
[I 210420 22:04:57 _device:947] WebDriverAgent start successfully
[D 210420 22:18:15 _relay:36] handle stream from: ('127.0.0.1', 61427)
[D 210420 22:18:15 _relay:36] handle stream from: ('127.0.0.1', 61429)
[D 210420 22:19:30 _relay:36] handle stream from: ('127.0.0.1', 61577)
[D 210420 22:20:41 _relay:36] handle stream from: ('127.0.0.1', 61715)
[D 210420 22:21:52 _relay:36] handle stream from: ('127.0.0.1', 61851)
[D 210420 22:23:04 _relay:36] handle stream from: ('127.0.0.1', 61999)
[D 210420 22:24:15 _relay:36] handle stream from: ('127.0.0.1', 62135)
[D 210420 22:25:26 _relay:36] handle stream from: ('127.0.0.1', 62270)
[D 210420 22:26:38 _relay:36] handle stream from: ('127.0.0.1', 62420)
[D 210420 22:27:49 _relay:36] handle stream from: ('127.0.0.1', 62570)
[D 210420 22:29:00 _relay:36] handle stream from: ('127.0.0.1', 62714)
[D 210420 22:30:10 _relay:36] handle stream from: ('127.0.0.1', 62860)
[D 210420 22:31:22 _relay:36] handle stream from: ('127.0.0.1', 62994)
[D 210420 22:32:33 _relay:36] handle stream from: ('127.0.0.1', 63143)
[D 210420 22:33:44 _relay:36] handle stream from: ('127.0.0.1', 63289)
[D 210420 22:34:56 _relay:36] handle stream from: ('127.0.0.1', 63436)
[I 210420 22:35:08 _device:1116] xctrunner quited
Exception in thread Thread-2:
Traceback (most recent call last):
  File "d:\python\python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "d:\python\python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "d:\python\python37\lib\site-packages\tidevice\_instruments.py", line 558, in _drain
    self._drain_single_message()
  File "d:\python\python37\lib\site-packages\tidevice\_instruments.py", line 578, in _drain_single_message
    mheader, payload = self.recv_dtx_message()
  File "d:\python\python37\lib\site-packages\tidevice\_instruments.py", line 499, in recv_dtx_message
    assert mheader.conversation_index in [0, 1, 2]
AttributeError: 'NoneType' object has no attribute 'conversation_index'

[I 210420 22:35:08 _wdaproxy:104] [00008030-0005119A1AE9802E] WDA keeper stopped
[I 210420 22:35:08 _wdaproxy:132] [00008030-0005119A1AE9802E] WDA stopped for the 5st time, running 30.2 minutes
[D 210420 22:35:08 _wdaproxy:116] [00008030-0005119A1AE9802E] launch WDA
[D 210420 22:35:08 _relay:36] handle stream from: ('127.0.0.1', 63471)
[E 210420 22:35:08 _relay:46] connect to device error: UsbmuxReplyCode.ConnectionRefused
[I 210420 22:35:08 _device:990] BundleID: com.facebook.WebDriverAgentRunner.lxytest.xctrunner
[I 210420 22:35:08 _device:992] DeviceIdentifier: 00008030-0005119A1AE9802E
[I 210420 22:35:08 _device:834] SignIdentity: 'Apple Development: 旭阳 吕 (G4QRHP58T3)'
[I 210420 22:35:08 _device:840] CFBundleExecutable: WebDriverAgentRunner-Runner
[D 210420 22:35:09 _relay:36] handle stream from: ('127.0.0.1', 63490)
[E 210420 22:35:09 _relay:46] connect to device error: UsbmuxReplyCode.ConnectionRefused
[I 210420 22:35:09 _device:871] AppContainer: /private/var/mobile/Containers/Data/Application/E8AF4528-27DD-48F2-B2BB-43E25BBDEC5E
[I 210420 22:35:09 _device:911] Launch 'com.facebook.WebDriverAgentRunner.lxytest.xctrunner' pid: 8788
[I 210420 22:35:09 _device:1086] ProductVersion: 14.0
[I 210420 22:35:09 _device:1041] Test runner ready detected
[I 210420 22:35:09 _device:1034] Start execute test plan with IDE version: 29
[D 210420 22:35:09 _relay:36] handle stream from: ('127.0.0.1', 63501)
[E 210420 22:35:09 _relay:46] connect to device error: UsbmuxReplyCode.ConnectionRefused
[I 210420 22:35:09 _device:947] WebDriverAgent start successfully
[D 210420 22:35:10 _relay:36] handle stream from: ('127.0.0.1', 63504)

# Appium Log
[W3C] Matched W3C error code 'invalid session id' to NoSuchDriverError
[BaseDriver] Waited for 2606 ms so far
[WD Proxy] Matched '/element' to command name 'findElement'
[WD Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/209E64C7-0DD6-4C52-A0C4-27AB74EA72A2/element] with body: {"using":"predicate string","value":"name==\"root_tab_calllog\""}
[WD Proxy] Got response with status 404: {"value":{"error":"invalid session id","message":"Session does not exist","traceback":"(\n\t0   CoreFoundation                      0x00000001832425c8 E6EA102C-3C74-3253-89A8-7C959E89197A + 1185224\n\t1   libobjc.A.dylib                     0x000000019723242c objc_exception_throw + 60\n\t2   CoreFoundation                      0x000000018314d63c E6EA102C-3C74-3253-89A8-7C959E89197A + 181820\n\t3   WebDriverAgentLib                   0x00000001065eaa68 -[FBRoute raiseNoSessionException] + 104\n\t4   WebDriverAgentLib                   0x00000001065ea99c -[FBRoute decorateRequest:] + 264\n\t5   WebDriverAgentLib                   0x00000001065e9cac -[FBRoute_TargetAction mountRequest:intoResponse:] + 108\n\t6   WebDriverAgentLib                   0x00000001065c8bf8 __37-[FBWebServer registerRouteHandlers:]_block_invoke + 500\n\t7   WebDriverAgentLib                   0x000000010660d224 -[RoutingHTTPServer handleRoute:withRequest:response:] + 184\n\t8   WebDriverAgentLib                   0x000000010660dd5c _...
[W3C] Matched W3C error code 'invalid session id' to NoSuchDriverError
[W3C (012630b2)] Encountered internal error running command: NoSuchElementError: An element could not be located on the page using the given search parameters.
[W3C (012630b2)]     at XCUITestDriver.doNativeFind (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-xcuitest-driver\lib\commands\find.js:126:11)
[W3C (012630b2)]     at processTicksAndRejections (internal/process/task_queues.js:85:5)
[HTTP] <-- POST /wd/hub/session/012630b2-a096-4dd5-9149-834017cc6b08/element 404 3124 ms - 486
[HTTP] 
[HTTP] --> GET /wd/hub/session/012630b2-a096-4dd5-9149-834017cc6b08/screenshot
[HTTP] {}
[W3C (012630b2)] Calling AppiumDriver.getScreenshot() with args: ["012630b2-a096-4dd5-9149-834017cc6b08"]
[XCUITest] Executing command 'getScreenshot'
[XCUITest] Taking screenshot with WDA
[WD Proxy] Matched '/screenshot' to command name 'getScreenshot'
[WD Proxy] Proxying [GET /screenshot] to [GET http://localhost:8100/session/209E64C7-0DD6-4C52-A0C4-27AB74EA72A2/screenshot] with no body
[WD Proxy] Got response with status 404: {"value":{"error":"invalid session id","message":"Session does not exist","traceback":"(\n\t0   CoreFoundation                      0x00000001832425c8 E6EA102C-3C74-3253-89A8-7C959E89197A + 1185224\n\t1   libobjc.A.dylib                     0x000000019723242c objc_exception_throw + 60\n\t2   CoreFoundation                      0x000000018314d63c E6EA102C-3C74-3253-89A8-7C959E89197A + 181820\n\t3   WebDriverAgentLib                   0x00000001065eaa68 -[FBRoute raiseNoSessionException] + 104\n\t4   WebDriverAgentLib                   0x00000001065ea99c -[FBRoute decorateRequest:] + 264\n\t5   WebDriverAgentLib                   0x00000001065e9cac -[FBRoute_TargetAction mountRequest:intoResponse:] + 108\n\t6   WebDriverAgentLib                   0x00000001065c8bf8 __37-[FBWebServer registerRouteHandlers:]_block_invoke + 500\n\t7   WebDriverAgentLib                   0x000000010660d224 -[RoutingHTTPServer handleRoute:withRequest:response:] + 184\n\t8   WebDriverAgentLib                   0x000000010660dd5c _...
[W3C] Matched W3C error code 'invalid session id' to NoSuchDriverError
[XCUITest] Error getting screenshot: Session does not exist
[XCUITest] Taking screenshot with WDA
[WD Proxy] Matched '/screenshot' to command name 'getScreenshot'
[WD Proxy] Proxying [GET /screenshot] to [GET http://localhost:8100/session/209E64C7-0DD6-4C52-A0C4-27AB74EA72A2/screenshot] with no body
[WD Proxy] Got response with status 404: {"value":{"error":"invalid session id","message":"Session does not exist","traceback":"(\n\t0   CoreFoundation                      0x00000001832425c8 E6EA102C-3C74-3253-89A8-7C959E89197A + 1185224\n\t1   libobjc.A.dylib                     0x000000019723242c objc_exception_throw + 60\n\t2   CoreFoundation                      0x000000018314d63c E6EA102C-3C74-3253-89A8-7C959E89197A + 181820\n\t3   WebDriverAgentLib                   0x00000001065eaa68 -[FBRoute raiseNoSessionException] + 104\n\t4   WebDriverAgentLib                   0x00000001065ea99c -[FBRoute decorateRequest:] + 264\n\t5   WebDriverAgentLib                   0x00000001065e9cac -[FBRoute_TargetAction mountRequest:intoResponse:] + 108\n\t6   WebDriverAgentLib                   0x00000001065c8bf8 __37-[FBWebServer registerRouteHandlers:]_block_invoke + 500\n\t7   WebDriverAgentLib                   0x000000010660d224 -[RoutingHTTPServer handleRoute:withRequest:response:] + 184\n\t8   WebDriverAgentLib                   0x000000010660dd5c _...
[W3C] Matched W3C error code 'invalid session id' to NoSuchDriverError
[XCUITest] Taking screenshot with WDA
[WD Proxy] Matched '/screenshot' to command name 'getScreenshot'
[WD Proxy] Proxying [GET /screenshot] to [GET http://localhost:8100/session/209E64C7-0DD6-4C52-A0C4-27AB74EA72A2/screenshot] with no body
[WD Proxy] Got response with status 404: {"value":{"error":"invalid session id","message":"Session does not exist","traceback":"(\n\t0   CoreFoundation                      0x00000001832425c8 E6EA102C-3C74-3253-89A8-7C959E89197A + 1185224\n\t1   libobjc.A.dylib                     0x000000019723242c objc_exception_throw + 60\n\t2   CoreFoundation                      0x000000018314d63c E6EA102C-3C74-3253-89A8-7C959E89197A + 181820\n\t3   WebDriverAgentLib                   0x00000001065eaa68 -[FBRoute raiseNoSessionException] + 104\n\t4   WebDriverAgentLib                   0x00000001065ea99c -[FBRoute decorateRequest:] + 264\n\t5   WebDriverAgentLib                   0x00000001065e9cac -[FBRoute_TargetAction mountRequest:intoResponse:] + 108\n\t6   WebDriverAgentLib                   0x00000001065c8bf8 __37-[FBWebServer registerRouteHandlers:]_block_invoke + 500\n\t7   WebDriverAgentLib                   0x000000010660d224 -[RoutingHTTPServer handleRoute:withRequest:response:] + 184\n\t8   WebDriverAgentLib                   0x000000010660dd5c _...
[W3C] Matched W3C error code 'invalid session id' to NoSuchDriverError
[W3C (012630b2)] Encountered internal error running command: NoSuchDriverError: Session does not exist
[W3C (012630b2)]     at errorFromW3CJsonCode (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:780:25)
[W3C (012630b2)]     at ProxyRequestError.getActualError (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:663:14)
[W3C (012630b2)]     at JWProxy.command (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\jsonwp-proxy\proxy.js:273:19)
[W3C (012630b2)]     at processTicksAndRejections (internal/process/task_queues.js:85:5)
[HTTP] <-- GET /wd/hub/session/012630b2-a096-4dd5-9149-834017cc6b08/screenshot 404 1043 ms - 701

**Comment by codeskyblue** [comment]
fixed in 0.7.12
