### ISSUE TITLE
关于打包WDA.ipa问题（About Package WebDriverAgent.ipa）

### ISSUE THREAD

**Issue by ZhouYixun** [alibaba/taobao-iphone-device#88]
有比较详细的从github拉下来的webdriveragent开始的打包步骤吗，我是从npm i appium下来的，在appium-webdriveragent里面执行了Script等等步骤，现在也是用xcode build的方式顺利跑了好几个月。
现在想采用这个tidevice的方案，但是打包时出现很多问题，跟着这个指令
`xcodebuild build-for-testing -workspace WebDriverAgent.xcworkspace/ -scheme WebDriverAgent -sdk iphoneos -configuration Release -derivedDataPath /tmp/derivedDataPath`
会出现以下问题
`xcodebuild: error: 'WebDriverAgent.xcworkspace/' does not exist.`

之后我尝试添加目录为xcode的workspace
![20210508145453](https://user-images.githubusercontent.com/56339314/117530021-80638000-b00d-11eb-856c-64cec4c66dd9.jpg)
![8F00C796-020F-40E3-8D5E-6DA15A4EBEE8](https://user-images.githubusercontent.com/56339314/117530024-82c5da00-b00d-11eb-8f56-1694c2d0efdb.png)

再执行，出现以下问题
`xcodebuild: error: The workspace named "WebDriverAgent" does not contain a scheme named "WebDriverAgent". The "-list" option can be used to find the names of the schemes in the workspace.`

最后将scheme改为WebDriverAgent-Runner，发现ipa执行不了

请问打包前的签名要用webdriveragent默认的，然后打完包再重签名？
还是打包前后都要重签名？因为跟之前传统方式有很多不一样的，希望作者能回答一下，感激不尽

**Comment by ZhouYixun** [comment]
https://github.com/alibaba/taobao-iphone-device/blob/main/DEVELOP.md
我参考的是作者这个步骤来的，就是不行

**Comment by electricbubble** [comment]
https://github.com/alibaba/taobao-iphone-device/issues/32

**Comment by ZhouYixun** [comment]
I follow the https://github.com/alibaba/taobao-iphone-device/blob/main/DEVELOP.md#how-to-package-wdaipa
but I get
`Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/tidevice", line 11, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tidevice/__main__.py", line 669, in main
    actions[args.subparser](args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tidevice/__main__.py", line 175, in cmd_parse
    ir.dump_info()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tidevice/_ipautil.py", line 70, in dump_info
    data = self.get_infoplist()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tidevice/_ipautil.py", line 55, in get_infoplist
    finfo = self.get_infoplist_zipinfo()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tidevice/_ipautil.py", line 26, in get_infoplist_zipinfo
    raise IPAError("Info.plist not found")
tidevice.exceptions.IPAError: Info.plist not found`


*.app contain IntegrationApp.app
my Release-iphoneos folder (after move file)
![20210508175547](https://user-images.githubusercontent.com/56339314/117535073-a77a7b80-b026-11eb-892c-aed23fd2571e.jpg)
my Payload folder
![20210508175711](https://user-images.githubusercontent.com/56339314/117535118-d7298380-b026-11eb-8ac3-a7758517542e.jpg)
xcode version: 14.2
webdriveragent version : newest

**Comment by ZhouYixun** [comment]
It work now,thanks!

**Comment by codeskyblue** [comment]
congratulations
