### ISSUE TITLE
【Advise】get app version

### ISSUE THREAD

**Issue by ZhouYixun** [alibaba/taobao-iphone-device#90]
I knew tidevice can replace parts of libimobiledevice now,but I wish I can get app version by tidevice.
`ideviceinstaller` can get `CFBundleIdentifier` `CFBundleShortVersionString` and `CFBundleVersion`
I wish I can use command to get them,look like
`tidevice applist --json`

**Comment by ZhouYixun** [comment]
> [#68 (comment)](https://github.com/alibaba/taobao-iphone-device/issues/68#issuecomment-819588748)

Thanks for your reply.
But I use Java language,can I use it in command?

**Comment by codeskyblue** [comment]
`tidevice appinfo com.apple.Preferences --json`

**Comment by ZhouYixun** [comment]
> `tidevice appinfo com.apple.Preferences --json`

thanks!
