### ISSUE TITLE
【HELP】Use it by Java

### ISSUE THREAD

**Issue by ZhouYixun** [alibaba/taobao-iphone-device#94]
I want to use `tidevice wdaproxy -B com.xxx.WebDriverAgentRunner.xctrunner --port 8200`
before test
and kill it after test.
But I use by
`Runtime.getRuntime().exec('tidevice wdaproxy -B com.xxx.WebDriverAgentRunner.xctrunner --port 8200')`
I cannot kill the process.
If I use .sh to run it,I would not kill three process: relay、xcrun and wdaproxy.

I wish I can use it in 50+ devices,so I must use it dynamically

**Comment by jongyu** [comment]
Use multi-threading and increase available port detection!!!

**Comment by ZhouYixun** [comment]
> Use multi-threading and increase available port detection!!!

but I use `tidevice wdaproxy -B com.xxx.WebDriverAgentRunner.xctrunner --port 8200` will increase three random pid,how can I kill them?

**Comment by codeskyblue** [comment]
send SIGTERM or SIGINT to the `tidevice wdaproxy`
