### ISSUE TITLE
【Advice】Export crash log

### ISSUE THREAD

**Issue by ZhouYixun** [alibaba/taobao-iphone-device#95]
Libimobiledevice can use idevicecrashreport to export the crash log from iphone.
I wish tidevice can do it in the future!

**Comment by jongyu** [comment]
Windows上也有这个库啊,可以先用着https://github.com/libimobiledevice-win32/imobiledevice-net/releases

**Comment by ZhouYixun** [comment]
> Windows上也有这个库啊,可以先用着https://github.com/libimobiledevice-win32/imobiledevice-net/releases

I hope tidevice can replace libimobiledevice in the future

**Comment by codeskyblue** [comment]
Pull request is welcome.
